services:
  el-project-grande-db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: el-project-grande-db
      MYSQL_USER: matezalantoth
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    env_file:
      - ./ElProjectGrande/.env

  db-setup-migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command: sh -c "cat /app/ElProjectGrande/ElProjectGrande.csproj && dotnet tool install --global dotnet-ef && /root/.dotnet/tools/dotnet-ef database update --project /app/ElProjectGrande/ElProjectGrande.csproj"
    depends_on:
      - el-project-grande-db
    volumes:
      - .:/app
    env_file:
      - ./ElProjectGrande/.env
    environment:
      - ConnectionStrings__MySql=Server=${DOCKER_SERVER_NAME};Database=${DB_NAME};User=${DB_USERNAME};Password=${DB_USER_PASSWORD};Port=${DB_PORT};


  el-project-grande-backend:
    image: elprojectgrande
    build:
      context: .
      dockerfile: ElProjectGrande/Dockerfile
    depends_on:
      - db-setup-migrate
    ports:
      - "8080:8080"
    env_file:
      - ./ElProjectGrande/.env
    volumes:
      - ".:/app"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MySql=Server=${DOCKER_SERVER_NAME};Database=${DB_NAME};User=${DB_USERNAME};Password=${DB_USER_PASSWORD};Port=${DB_PORT};